import { ArrowRight, Camera, Code2, Download, Film, Layers3, Palette, Sparkles } from "lucide-react";
import { Link } from "react-router";
import { motion, useReducedMotion } from "motion/react";
import portrait from "../../../imports/fazri.png";
import { usePortfolioData } from "../../hooks/usePortfolioData";

const journey = [
  ["01", "Early interest in technology", "Curiosity about systems, digital tools, and how a clear interface can make complex tasks feel simple."],
  ["02", "Learning web development", "Building a foundation in responsive UI, JavaScript, databases, and product-oriented thinking."],
  ["03", "Academic & client projects", "Turning briefs into dashboards, learning tools, and digital processes that support real work."],
  ["04", "Expanding visual practice", "Bringing UI design, photography, videography, and editing into the same problem-solving workflow."],
  ["05", "Current focus", "Creating polished web experiences with modern animation, stronger systems thinking, and dimensional interaction."],
];
const values = ["Useful before ornamental", "Careful with the details", "Clear communication throughout", "Always learning in public"];
function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { const reduce = useReducedMotion(); return <motion.div initial={reduce ? false : { opacity: 0, y: 25 }} whileInView={reduce ? {} : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ duration: .65 }} className={className}>{children}</motion.div>; }
function Label({ children }: { children: React.ReactNode }) { return <p className="mb-4 font-mono text-[10px] uppercase tracking-[.2em] text-[var(--color-accent-main)]">{children}</p>; }

export default function AboutPage() {
  const { profile } = usePortfolioData();
  const aboutImage = profile.aboutImageUrl || portrait;

  return (
    <main className="overflow-x-clip bg-[var(--color-bg-primary)] pt-24 text-[var(--color-text-main)] sm:pt-28">
    <section className="relative border-b border-[var(--color-border)] px-5 pb-20 pt-10 sm:px-6 sm:pb-24 sm:pt-14 lg:pb-32"><div className="absolute right-0 top-0 h-full w-1/3 bg-[radial-gradient(ellipse_at_100%_35%,rgba(78,187,232,.15),transparent_60%)]" /><div className="relative mx-auto max-w-7xl"><Reveal><Label>About / Fazri Lukman Nurrohman</Label><h1 className="max-w-3xl font-manrope text-4xl font-bold leading-[1.02] tracking-[-.035em] sm:text-5xl md:text-7xl">Building useful digital experiences with a creative point of view.</h1></Reveal><div className="mt-10 grid items-center gap-12 sm:mt-14 lg:mt-16 lg:grid-cols-[.95fr_1.05fr] lg:gap-20"><Reveal className="relative min-h-[440px] sm:min-h-[530px]"><div className="absolute inset-0 border border-[var(--color-border)] bg-[var(--color-surface-elevated)]"><img src={aboutImage} onError={(event) => { event.currentTarget.src = portrait; }} alt="Fazri wearing a suit" className="h-full w-full object-contain object-center grayscale transition duration-700 hover:grayscale-0" /></div><span className="absolute bottom-3 right-3 border border-[var(--color-border)] bg-[var(--color-bg-primary)] px-4 py-3 font-mono text-[9px] tracking-widest text-[var(--color-accent-main)] sm:-bottom-5 sm:right-6 sm:px-5 sm:py-4 sm:text-[10px]">INDONESIA / GMT+7</span></Reveal><Reveal><Label>Hello, I'm</Label><h2 className="font-manrope text-2xl font-bold sm:text-3xl">Fazri Lukman Nurrohman</h2><p className="mt-6 max-w-xl text-base leading-7 text-[var(--color-text-secondary)] sm:text-lg sm:leading-8">A Creative Web Developer who enjoys turning ambiguous ideas into clear, useful, and visually considered web experiences.</p><p className="mt-5 max-w-xl leading-7 text-[var(--color-text-muted)]">My work blends web development with an appreciation for interface design, photography, videography, and visual editing. The result is a practice that pays attention to how a product works, looks, and communicates.</p><blockquote className="mt-8 border-l-2 border-[var(--color-accent-main)] bg-[var(--color-surface-elevated)] px-5 py-5 text-lg leading-8 text-[var(--color-accent-silver)] sm:px-6 sm:text-xl">"Technology becomes more meaningful when functionality, design, and visual storytelling work together."</blockquote><div className="mt-8 flex flex-wrap gap-3"><a href="#cv" className="inline-flex items-center gap-2 bg-[var(--color-text-main)] px-5 py-3 text-sm font-bold text-[var(--color-bg-primary)]"><Download size={15} />Download CV</a><Link to="/projects" className="inline-flex items-center gap-2 border border-[var(--color-border)] px-5 py-3 text-sm font-bold">View Projects <ArrowRight size={15} /></Link></div></Reveal></div></div></section>
    <section className="bg-[var(--color-bg-secondary)] px-5 py-20 sm:px-6 sm:py-24"><div className="mx-auto max-w-7xl"><Reveal><Label>My practice</Label><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr] lg:gap-10"><h2 className="font-manrope text-3xl font-bold sm:text-4xl">A development focus supported by a broader visual toolkit.</h2><p className="max-w-xl leading-7 text-[var(--color-text-secondary)] sm:leading-8">I'm most engaged when the development process is close to the problem: clarifying what people need, shaping the interface around that need, then refining the build until it feels reliable and natural to use.</p></div></Reveal><div className="mt-12 grid gap-px border border-[var(--color-border)] bg-[var(--color-border)] md:mt-14 md:grid-cols-3">{[[Code2, "Web Development", "Responsive frontends, data-driven applications, dashboards, and deployment-ready builds."], [Palette, "UI Design", "Interface structure, visual hierarchy, and practical design systems for implementation."], [Camera, "Visual Production", "Photography, video, and editing that give digital stories texture and focus."]].map(([Icon, title, text]) => <Reveal key={String(title)} className="bg-[var(--color-bg-secondary)] p-6 sm:p-7"><Icon className="text-[var(--color-accent-main)]" size={23} /><h3 className="mt-9 font-manrope text-xl font-bold sm:mt-12">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-[var(--color-text-muted)]">{String(text)}</p></Reveal>)}</div></div></section>
    <section className="px-6 py-24"><div className="mx-auto max-w-7xl"><Reveal><Label>Capability ecosystem</Label><h2 className="font-manrope text-4xl font-bold">One central focus. Five supporting disciplines.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-3"><Reveal className="relative flex min-h-[360px] items-center justify-center overflow-hidden border border-[var(--color-border)] bg-[var(--color-surface-elevated)] md:col-span-2"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.09)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.09)_1px,transparent_1px)] [background-size:32px_32px]" /><div className="relative border border-[var(--color-accent-main)] bg-[var(--color-bg-primary)] px-10 py-9 text-center"><Code2 className="mx-auto text-[var(--color-accent-main)]" /><strong className="mt-3 block font-manrope text-2xl">Web Development</strong><span className="mt-1 block text-sm text-[var(--color-text-muted)]">The centre of the practice</span></div></Reveal><div className="grid gap-4">{[[Palette, "UI Design", "Figma artboard"], [Camera, "Photography", "Camera frame"], [Film, "Video & Editing", "Editing timeline"], [Layers3, "Visual Systems", "Browser interface"]].map(([Icon, name, caption]) => <Reveal key={String(name)} className="flex items-center gap-4 border border-[var(--color-border)] bg-[var(--color-bg-secondary)] p-5"><Icon size={19} className="text-[var(--color-accent-main)]" /><div><h3 className="font-semibold">{String(name)}</h3><p className="mt-1 text-xs text-[var(--color-text-muted)]">{String(caption)}</p></div></Reveal>)}</div></div></div></section>
    <section className="bg-[var(--color-surface-elevated)] px-6 py-24"><div className="mx-auto max-w-7xl"><Reveal><Label>Journey</Label><h2 className="font-manrope text-4xl font-bold">A practice shaped by making.</h2></Reveal><div className="mt-12 grid gap-px border border-[var(--color-border)] bg-[var(--color-border)]">{journey.map(([number, title, description]) => <Reveal key={number} className="grid gap-5 bg-[var(--color-surface-elevated)] p-6 transition hover:bg-[var(--color-bg-secondary)] md:grid-cols-[100px_1fr_1fr]"><span className="font-mono text-sm text-[var(--color-accent-main)]">{number}</span><h3 className="font-manrope text-xl font-bold">{title}</h3><p className="text-sm leading-6 text-[var(--color-text-secondary)]">{description}</p></Reveal>)}</div></div></section>
    <section className="px-6 py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><Reveal><Label>Values & workflow</Label><h2 className="font-manrope text-4xl font-bold">A considered process, from first conversation to final detail.</h2><div className="mt-9 grid gap-3 sm:grid-cols-2">{values.map((value, index) => <div key={value} className="border-b border-[var(--color-border)] py-4"><span className="font-mono text-[10px] text-[var(--color-accent-main)]">0{index + 1}</span><p className="mt-2 font-semibold">{value}</p></div>)}</div></Reveal><Reveal className="border border-[var(--color-border)] bg-[var(--color-bg-secondary)] p-8"><Label>Tools I reach for</Label><div className="mt-8 flex flex-wrap gap-2">{["React", "Vite", "Tailwind CSS", "Laravel", "Supabase", "GitHub", "Figma", "Photoshop", "Premiere Pro", "Blender"].map((tool) => <span key={tool} className="border border-[var(--color-border)] px-3 py-2 text-sm text-[var(--color-text-secondary)]">{tool}</span>)}</div><p className="mt-10 leading-7 text-[var(--color-text-muted)]">The tools evolve. The constant is a workflow built around clear feedback, intentional structure, and time for refinement.</p></Reveal></div><div className="mt-16 grid gap-px border border-[var(--color-border)] bg-[var(--color-border)] md:grid-cols-3">{[["10+", "Projects delivered"], ["8+", "Certificates earned"], ["2+", "Years learning & shipping"]].map(([stat, label]) => <Reveal key={label} className="bg-[var(--color-bg-primary)] p-7"><strong className="font-manrope text-5xl text-[var(--color-accent-main)]">{stat}</strong><p className="mt-2 text-sm text-[var(--color-text-secondary)]">{label}</p></Reveal>)}</div></section>
    <section className="bg-[radial-gradient(ellipse_at_80%_100%,rgba(78,187,232,.18),transparent_50%),var(--color-bg-secondary)] px-5 py-20 sm:px-6 sm:py-24"><Reveal className="mx-auto max-w-3xl text-center"><Sparkles className="mx-auto text-[var(--color-accent-main)]" /><h2 className="mt-6 font-manrope text-4xl font-bold tracking-[-.035em] sm:text-5xl">Let's create a clear next step.</h2><p className="mt-5 text-[var(--color-text-secondary)]">Whether you are planning a system, shaping a product, or refining an experience, I'd love to hear the context.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/contact" className="bg-[var(--color-text-main)] px-5 py-3 text-sm font-bold text-[var(--color-bg-primary)]">Contact Me</Link><Link to="/projects" className="border border-[var(--color-border)] px-5 py-3 text-sm font-bold">View Projects</Link></div></Reveal></section>
    </main>
  );
}

